exports.seed = function (knex) {
    // Deletes ALL existing entries
    return knex('employees').del()
        .then(function () {
            // Inserts seed entries
            return knex('employees').insert([
                {
                    id: 1,
                    first_name: 'John',
                    last_name: 'Doe',
                    email_address: 'johndoe@example.com',
                    phone_number: '1234567890',
                    lat: 43.654321,
                    lng: -79.383758,
                    status: "online",
                    title: "Technician",
                },
                {
                    id: 2,
                    first_name: 'Jane',
                    last_name: 'Doe',
                    email_address: 'janedoe@example.com',
                    phone_number: '1234567890',
                    lat: 43.6680169,
                    lng: -79.4063909,
                    status: "busy",
                    title: "Engineer",
                },
                {
                    id: 3,
                    first_name: 'Bob',
                    last_name: 'Smith',
                    email_address: 'bobsmith@example.com',
                    phone_number: '9876543210',
                    lat: 43.643352,
                    lng: -79.383758,
                    status: "offline",
                    title: "Manager",
                },
                {
                    id: 4,
                    first_name: 'Alice',
                    last_name: 'Johnson',
                    email_address: 'alicejohnson@example.com',
                    phone_number: '1234567890',
                    lat: 43.654321,
                    lng: -79.360987,
                    status: "online",
                    title: "Technician",
                },
                {
                    id: 5,
                    first_name: 'David',
                    last_name: 'Brown',
                    email_address: 'davidbrown@example.com',
                    phone_number: '1234567890',
                    lat: 43.678901,
                    lng: -79.389765,
                    status: "busy",
                    title: "Engineer",
                },
                {
                    id: 6,
                    first_name: 'Emily',
                    last_name: 'Davis',
                    email_address: 'emilydavis@example.com',
                    phone_number: '9876543210',
                    lat: 43.654321,
                    lng: -79.410987,
                    status: "offline",
                    title: "Manager",
                },
                {
                    id: 7,
                    first_name: 'Michael',
                    last_name: 'Wilson',
                    email_address: 'michaelwilson@example.com',
                    phone_number: '1234567890',
                    lat: 43.654321,
                    lng: -79.438765,
                    status: "online",
                    title: "Technician",
                },
                {
                    id: 8,
                    first_name: 'Olivia',
                    last_name: 'Taylor',
                    email_address: 'oliviataylor@example.com',
                    phone_number: '1234567890',
                    lat: 43.654321,
                    lng: -79.421987,
                    status: "busy",
                    title: "Engineer",
                },
                {
                    id: 9,
                    first_name: 'William',
                    last_name: 'Anderson',
                    email_address: 'williamanderson@example.com',
                    phone_number: '9876543210',
                    lat: 43.654321,
                    lng: -79.394765,
                    status: "offline",
                    title: "Manager",
                },
                {
                    id: 10,
                    first_name: 'Sophia',
                    last_name: 'Thomas',
                    email_address: 'sophiathomas@example.com',
                    phone_number: '1234567890',
                    lat: 43.654321,
                    lng: -79.360987,
                    status: "online",
                    title: "Technician",
                },
                {
                    id: 11,
                    first_name: 'James',
                    last_name: 'Jackson',
                    email_address: 'jamesjackson@example.com',
                    phone_number: '1234567890',
                    lat: 43.654321,
                    lng: -79.338765,
                    status: "busy",
                    title: "Engineer",
                },
                {
                    id: 12,
                    first_name: 'Ava',
                    last_name: 'White',
                    email_address: 'avawhite@example.com',
                    phone_number: '9876543210',
                    lat: 43.6357769,
                    lng: -79.4267949,
                    status: "offline",
                    title: "Manager",
                },
                {
                    id: 13,
                    first_name: 'Benjamin',
                    last_name: 'Harris',
                    email_address: 'benjaminharris@example.com',
                    phone_number: '1234567890',
                    lat: 43.666,
                    lng: -79.395,
                    status: "online",
                    title: "Technician",
                },
                {
                    id: 14,
                    first_name: 'Mia',
                    last_name: 'Martin',
                    email_address: 'miamartin@example.com',
                    phone_number: '1234567890',
                    lat: 43.667,
                    lng: -79.396,
                    status: "busy",
                    title: "Engineer",
                }
            ]);
        });
};